scopes = "read_products,read_themes"

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://trustscore-scanne-production.up.railway.app/api/webhooks"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://trustscore-scanne-production.up.railway.app/api/webhooks"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "https://trustscore-scanne-production.up.railway.app/api/webhooks"
